version: '3'

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./docker/php-fpm
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - "./:/var/www"

  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./docker/nginx
    volumes:
      - "./:/var/www"
    depends_on:
      - php-fpm
    ports:
      - "80:80"